Update testing.yaml

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -1,91 +1,63 @@
-name: Step 0, Welcome
+name: Automate Git Actions
 
-# This step triggers after the learner creates a new repository from the template.
-# This workflow updates from step 0 to step 1.
-
-# This will run every time we create push a commit to `main`.
-# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - main
-
-# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
-permissions:
-  # Need `contents: read` to checkout the repository.
-  # Need `contents: write` to update the step metadata.
-  contents: write
+    inputs:
+      repository_name:
+        description: 'Repository Name'
+        required: true
+      new_branch_name:
+        description: 'New Branch Name'
+        required: true
+      commit_message:
+        description: 'Commit Message'
+        required: true
+      user_email:
+        description: 'User Email'
+        required: true
+      user_name:
+        description: 'User Name'
+        required: true
 
 jobs:
-  # Get the current step to only run the main job when the learner is on the same step.
-  get_current_step:
-    name: Check current step number
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - id: get_step
-        run: |
-          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
-    outputs:
-      current_step: ${{ steps.get_step.outputs.current_step }}
-
-  on_start:
-    name: On start
-    needs: get_current_step
-
-    # We will only run this action when:
-    # 1. This repository isn't the template repository.
-    # 2. The step is currently 0.
-    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
-    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
-    if: >-
-      ${{ !github.event.repository.is_template
-          && needs.get_current_step.outputs.current_step == 0 }}
-
-    # We'll run Ubuntu for performance instead of Mac or Windows.
+  automate:
     runs-on: ubuntu-latest
 
+    env:
+      REPOSITORY_NAME: ${{ github.event.inputs.repository_name }}
+      NEW_BRANCH_NAME: ${{ github.event.inputs.new_branch_name }}
+      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
+      USER_EMAIL: ${{ github.event.inputs.user_email }}
+      USER_NAME: ${{ github.event.inputs.user_name }}
+      
     steps:
-      # We'll need to check out the repository so that we can edit the README.
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Let's get all the branches.
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      # Make a branch, file, and commit for the learner.
-      - name: Prepare a branch, and file
-        run: |
-          echo "Make sure we are on step 0"
-          if [ "$(cat .github/steps/-step.txt)" != 0 ]
-          then
-            echo "Current step is not 0"
-            exit 0
-          fi
+    - name: Configure Git
+      run: |
+        git config user.email "${{ env.USER_EMAIL }}"
+        git config user.name "${{ env.USER_NAME }}"
+        git config push.default current
 
-          echo "Make a branch"
-          BRANCH=welcome-workflow
-          git checkout -b $BRANCH
+    - name: Create and switch to a new branch
+      run: git checkout -b ${{ env.NEW_BRANCH_NAME }}
 
-          echo "Make a commit"
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git commit --allow-empty --message="Create an empty commit"
+    # Do the required changes
 
-          echo "Push"
-          git push --set-upstream origin $BRANCH
+    - name: Commit changes
+      run: |
+        git add .
+        git commit -m "${{ env.COMMIT_MESSAGE }}"
 
-          echo "Restore main"
-          git checkout main
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Check if there are no uncommitted changes
+      run: |
+        if [[ -z $(git status --porcelain) ]]; then
+          echo "No changes to commit. Proceeding to push."
+        else
+          echo "Error: There are uncommitted changes. Please commit or discard them."
+          exit 1
+        fi
 
-      # In README.md, switch step 0 for step 1.
-      - name: Update to step 1
-        uses: skills/action-update-step@v2
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          from_step: 0
-          to_step: 1
-          branch_name: welcome-workflow
+    - name: Push changes
+      run: git push origin ${{ env.NEW_BRANCH_NAME }}
